# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InsarExplorer
                                 A QGIS plugin
 InSAR Explorer is a QGIS plugin that allows for dynamic visualization and analysis of InSAR time series data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-01
        copyright            : (C) 2024-2026 by Mahmud Haghighi
        email                : insar-explorer@eodeck.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__version__ = "2.9.0"
__date__ = "2026.08.24"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InsarExplorer class from file InsarExplorer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .insar_explorer import InsarExplorer
    return InsarExplorer(iface)


# Initialize runtime compatibility patches for supported QGIS/Qt versions.
# This must run before the plugin imports or uses patched components.
from .src.pyqtgraph_compat import applyPyqtgraphCompatPatches  # noqa: E402
applyPyqtgraphCompatPatches()
